kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: gradle:jdk8
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    commands:
      - "export GRADLE_USER_HOME=$PWD/.gradle"
      - ./gradlew jar

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_KEY
      files: build/libs/*
    when:
      event: tag
